### ISSUE TITLE
Conductor Resistance Adjustment for Temperature

### ISSUE THREAD

**Issue by gall9488** [bt-/pySolarCalc#4]
Chapter 9, Table 8, Note 2 for resistance changes due to temperature.

I propose we perform adjustments based on conductor insulation rating because as the conductor heats up, the resistance also increases. Assuming resistance values for the full rating of the conductor insulation will ensure we are taking a conservative approach for all use cases of that conductor.

**Comment by gall9488** [comment]
Also applicable to Chapter 9, Table 9, (AC Values) due to Note 1 statement. Will need to adjust for temperatures other than 75°C.

**Comment by bt-** [comment]
moved to projects
